### ISSUE TITLE
Support custom metrics

### ISSUE THREAD

**Issue by vdogaru** [quarks-edge/quarks#117]
The current system provides the following metrics: tuple counter (number of tuples since topology submission) and tuple meter (mean throughput and moving averages).

Using other metrics from the Java metrics package is currently supported. What is needed is sample code to demonstrated this, maybe in the form of:
- Oplets wrapping Java metrics, which can be inserted into the application topology.
- Functions using Java metrics directly.

**Comment by xuanyue202** [comment]
I believe currently from console side, Quarks only support the display of Meter and Counter metrics. If you register a Gauge, for example, into Quarks, there would be no entry in the Console to show it. Second, it is also very hard in the current framework to define custom MBeans. Say if I want to have two meters in  one oplet to monitor two different KPIs, I would like to define my own MBeans to wrap the two meters in order to give meaningful monitoring results (e.g. field names).

**Comment by vdogaru** [comment]
True, Quarks provides meter and counter metrics encapsulated in Oplet implementations and an extension point (SingleMetricAbstractOplet).

These metrics are exposed via JMX and directly from the metric registry.  For example, here is the ObjectName of a tuple meter:
`quarks.providers.development:jobId=JOB_0,opId=OP_10,name=TupleCounter.quarks.oplet.JOB_0.OP_10,type=metric.counters`.  You can parse the Job ID, Oplet ID, and metric type from here.
Metrics can also be accessed directly from the `MetricRegistry` passed by the application.  See `quarks.samples.utils.metrics.PeriodicSourceWithMetrics` for an example which sets up the registry before submitting a topology.

For your other examples, I'm investigating the following scenarios:
- Using metrics in lambda functions
- Define oplet which encapsulates multiple metrics
- Metric naming: as an application developer I'd like to assign a logical name to a metric when I declare my topology and access the metric at run time using that name

This issue has moved to Apache, please check https://issues.apache.org/jira/browse/QUARKS-11 for updates.
